### ISSUE TITLE
Invalid Node names

### ISSUE THREAD

**Issue by whatsupskip** [emoncms/postprocess#11]
Emoncms V9.9.8 It appears that at least several actions in the Post Process module create invalid Feed names. Actually the Feed name itself is fine it is just they are placed in the “NoGroup”. This “NoGroup” appears to be invalid as any Feeds within this can’t be graphed.

I have tested with “powertokwh” and “mergefeeds”.

![](https://community.openenergymonitor.org/uploads/default/original/2X/1/15ed238de22815238a85f25a1a9a758c3c83c7b5.jpeg)

I haven’t found any way to rename Nodes or move feeds to an existing Node, so it would appear the best fix would be to allow the selection of an existing Node as part of the Post Process interface.

I tried editing/correcting the Feed name via the Feeds table in the MySQL data base. Even though I was able to change the name in the database it did not change in the local Emoncms.

**Comment by TrystanLea** [comment]
Testing on emoncms 10, moving feeds created by the post process module using the feed edit facility seems to be working ok. Please re-open if needed.
