### ISSUE TITLE
Running process feedback required 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/postprocess#17]
Currently, when a process is running there is no user feedback

**Comment by alexandrecuer** [comment]
if you are in Auto refresh, the logger is giving real time feedback

before updating a process : 
![image](https://user-images.githubusercontent.com/24553739/64064504-af9fd800-cc02-11e9-9908-761bbffc9dcf.png)

during and after the update 
![image](https://user-images.githubusercontent.com/24553739/64064521-f8579100-cc02-11e9-86b6-402a3916db7e.png)

**Comment by glynhudson** [comment]
Ah, good to know. I must have had auto refresh turned off
