### ISSUE TITLE
Parse error: syntax error, unexpected '=>' in latest version of postprocess

### ISSUE THREAD

**Issue by glynhudson** [emoncms/postprocess#29]
I've just updated the latest version of postprocess on an emonPi running `emonSD-21Jul21` with PHP Version 7.3.31-1~deb10u1` and I get the following error 

`Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /opt/emoncms/modules/postprocess/postprocess-module/postprocess_model.php on line 222`

This is the line in question which looks ok

`usort($processes, fn($a, $b) => $a['order'] <=> $b['order']);`

https://github.com/emoncms/postprocess/blob/master/postprocess-module/postprocess_model.php#L222C8-L222C70

However, on an emonPi running `emonSD-10Nov22` with `PHP Version 8.1.13` it works fine.

**Comment by TrystanLea** [comment]
I've fixed this one now, should be php7 compatible
